# Use the official Golang image from the Docker Hub
FROM golang:alpine3.20

# Set the working directory
WORKDIR /app

# Copy the source code
COPY . .

# Build the application
RUN go build -o myapp .

# Run the application
CMD ["./myapp"]

